"use client";
import { useState, useMemo } from "react";
import { api } from "@/lib/api";
import { useApi } from "@/hooks/useApi";
import Card from "@/components/Card";
import LoadingSpinner from "@/components/LoadingSpinner";
import { formatDateTime } from "@/lib/utils";
import { ALERT_TYPE_COLORS, ALERT_SEVERITY_COLORS } from "@/lib/thresholds";
import { Bell, AlertTriangle, ShieldAlert, Siren, Search, X, Filter, CheckCircle, TrendingUp, Clock, Trash2, ShieldOff } from "lucide-react";
import {
  AreaChart, Area, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip,
  Legend, ResponsiveContainer, Cell,
} from "recharts";

// Only types actually generated by the system
const TYPES = [
  { value: "", label: "Tous les types" },
  { value: "flood",       label: "Inondation",       icon: "💧" },
  { value: "air_quality", label: "Qualité de l'air", icon: "💨" },
  { value: "heat_wave",   label: "Canicule",          icon: "🌡️" },
  { value: "drought",     label: "Sécheresse",        icon: "☀️" },
];

// Severity scale — only levels actually generated by the system
const SEVERITIES = [
  { value: "",         label: "Toutes sévérités", desc: "" },
  { value: "warning",  label: "Avertissement",    desc: "Populations sensibles à risque — vigilance recommandée" },
  { value: "danger",   label: "Danger",           desc: "Risque élevé — actions préventives nécessaires" },
  { value: "critical", label: "Critique",         desc: "Urgence — actions immédiates requises" },
];

const SEVERITY_FR: Record<string, string> = {
  info:     "Surveillance",
  warning:  "Avertissement",
  danger:   "Danger",
  critical: "Critique",
};

const severityStyle: Record<string, string> = {
  info:     "border-l-blue-400 bg-blue-50/40",
  warning:  "border-l-yellow-500 bg-yellow-50/40",
  danger:   "border-l-orange-500 bg-orange-50/40",
  critical: "border-l-red-600 bg-red-50/40",
};

const severityBadge: Record<string, string> = {
  info:     "bg-blue-100 text-blue-700 border-blue-200",
  warning:  "bg-yellow-100 text-yellow-700 border-yellow-200",
  danger:   "bg-orange-100 text-orange-700 border-orange-200",
  critical: "bg-red-100 text-red-700 border-red-200",
};

const typeBadge: Record<string, string> = {
  flood:       "bg-blue-100 text-blue-700 border-blue-200",
  air_quality: "bg-teal-100 text-teal-700 border-teal-200",
  heat_wave:   "bg-red-100 text-red-700 border-red-200",
  drought:     "bg-amber-100 text-amber-700 border-amber-200",
};

const TYPE_LABELS: Record<string, string> = {
  flood:       "Inondation",
  air_quality: "Qualité de l'air",
  heat_wave:   "Canicule",
  drought:     "Sécheresse",
};

function formatDuration(start: string, end?: string): string {
  const from = new Date(start).getTime();
  const to = end ? new Date(end).getTime() : Date.now();
  const diffMs = to - from;
  if (diffMs < 0) return "";
  const totalMin = Math.floor(diffMs / 60000);
  const days = Math.floor(totalMin / 1440);
  const hours = Math.floor((totalMin % 1440) / 60);
  const mins = totalMin % 60;
  if (days > 0) return `${days}j ${hours}h`;
  if (hours > 0) return `${hours}h ${mins}min`;
  return `${mins} min`;
}

export default function AlertsPage() {
  const [filterType, setFilterType] = useState("");
  const [filterSeverity, setFilterSeverity] = useState("");
  const [filterActive, setFilterActive] = useState<"true" | "false" | "">( "true");
  const [search, setSearch] = useState("");
  const [resolving, setResolving] = useState<string | null>(null);
  const [resolvedIds, setResolvedIds] = useState<Set<string>>(new Set());
  const [deletedIds, setDeletedIds] = useState<Set<string>>(new Set());
  const [deleting, setDeleting] = useState<string | null>(null);
  const [resolvingAll, setResolvingAll] = useState(false);
  const [historyDays, setHistoryDays] = useState(30);

  const histStats = useApi(() => api.getAlertHistoryStats(historyDays), [historyDays], "alerts-history");

  const handleResolve = async (id: string) => {
    setResolving(id);
    try {
      await api.resolveAlert(id);
      setResolvedIds(prev => new Set([...prev, id]));
      stats.refetch();
      histStats.refetch();
    } catch {}
    finally { setResolving(null); }
  };

  const handleDelete = async (id: string) => {
    setDeleting(id);
    try {
      await api.deleteAlert(id);
      setDeletedIds(prev => new Set([...prev, id]));
      stats.refetch();
    } catch {}
    finally { setDeleting(null); }
  };

  const handleResolveAll = async () => {
    setResolvingAll(true);
    try {
      const r = await api.resolveAllAlerts();
      alerts.refetch();
      stats.refetch();
      histStats.refetch();
    } catch {}
    finally { setResolvingAll(false); }
  };

  const params = useMemo(() => {
    const p: Record<string, string> = { limit: "200" };
    if (filterType) p.alert_type = filterType;
    if (filterSeverity) p.severity = filterSeverity;
    if (filterActive !== "") p.active = filterActive;  // "true" | "false"
    return p;
  }, [filterType, filterSeverity, filterActive]);

  const alerts = useApi(() => api.getAlerts(params), [JSON.stringify(params)], "alerts-list");
  const stats = useApi(() => api.getAlertStats(), [], "alerts-stats");

  const SEVERITY_ORDER: Record<string, number> = { critical: 0, danger: 1, warning: 2, info: 3 };

  const filtered = useMemo(() => {
    const list: any[] = (Array.isArray(alerts.data?.data) ? alerts.data?.data : [])
      .filter((a: any) => !resolvedIds.has(a.id) && !deletedIds.has(a.id));
    const searched = !search.trim() ? list : list.filter(a =>
      a.title?.toLowerCase().includes(search.toLowerCase()) ||
      a.description?.toLowerCase().includes(search.toLowerCase()) ||
      a.locations?.name?.toLowerCase().includes(search.toLowerCase())
    );
    // Sort: active first, then by severity, then by start_date desc
    return [...searched].sort((a, b) => {
      if (a.is_active !== b.is_active) return a.is_active ? -1 : 1;
      const sa = SEVERITY_ORDER[a.severity] ?? 9;
      const sb = SEVERITY_ORDER[b.severity] ?? 9;
      if (sa !== sb) return sa - sb;
      return new Date(b.start_date || b.created_at).getTime() - new Date(a.start_date || a.created_at).getTime();
    });
  }, [alerts.data, search, resolvedIds, deletedIds]);

  const hasFilters = filterType || filterSeverity || filterActive !== "true" || search;

  const resetFilters = () => {
    setFilterType("");
    setFilterSeverity("");
    setFilterActive("true");
    setSearch("");
  };

  const severityIcon: Record<string, any> = {
    warning:  <AlertTriangle className="w-4 h-4 text-yellow-500" />,
    danger:   <ShieldAlert className="w-4 h-4 text-orange-500" />,
    critical: <Siren className="w-4 h-4 text-red-500" />,
  };

  return (
    <div className="space-y-6 animate-fade-in">
      <div>
        <h1 className="text-2xl font-bold flex items-center gap-2">
          <Bell className="w-7 h-7 text-danger" /> Alertes Environnementales
        </h1>
        <p className="text-sm text-text-secondary mt-1">Alertes actives et historique des événements</p>
      </div>

      {/* Stats */}
      {stats.data?.data && (
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          <div className="bg-card border border-border rounded-xl p-4 text-center">
            <p className="text-2xl font-bold text-danger">{stats.data.data.total_active || 0}</p>
            <p className="text-xs text-text-muted mt-1">Alertes actives</p>
          </div>
          {Object.entries(stats.data.data.by_type || {}).map(([type, count]) => (
            <div key={type} className="bg-card border border-border rounded-xl p-4 text-center cursor-pointer hover:ring-2 hover:ring-primary/30 transition"
              onClick={() => setFilterType(prev => prev === type ? "" : type)}>
              <p className="text-2xl font-bold text-text">{String(count)}</p>
              <p className="text-xs text-text-muted mt-1 capitalize">{TYPE_LABELS[type] || type.replace("_", " ")}</p>
            </div>
          ))}
        </div>
      )}

      {/* History Charts */}
      <div className="bg-card border border-border rounded-xl p-5">
        <div className="flex items-center justify-between mb-4 flex-wrap gap-3">
          <div className="flex items-center gap-2">
            <TrendingUp className="w-4 h-4 text-primary" />
            <h3 className="text-sm font-semibold text-text">Historique des alertes</h3>
            {histStats.data && (
              <span className="text-xs text-text-muted">· {histStats.data.total} alertes sur {histStats.data.days} jours</span>
            )}
          </div>
          <div className="flex items-center gap-1 rounded-lg border border-border overflow-hidden text-xs">
            {[7, 14, 30, 60].map(d => (
              <button key={d} onClick={() => setHistoryDays(d)}
                className={`px-3 py-1.5 transition ${historyDays === d ? "bg-primary text-white" : "bg-background text-text hover:bg-border/30"}`}>
                {d}j
              </button>
            ))}
          </div>
        </div>

        {histStats.loading ? (
          <div className="h-48 flex items-center justify-center text-text-muted text-sm">Chargement...</div>
        ) : histStats.data ? (
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            {/* Timeline AreaChart — takes 2/3 */}
            <div className="lg:col-span-2">
              <p className="text-xs text-text-muted mb-2">Alertes déclenchées par jour</p>
              <ResponsiveContainer width="100%" height={200}>
                <AreaChart data={histStats.data.timeline} margin={{ top: 4, right: 8, left: -20, bottom: 0 }}>
                  <defs>
                    <linearGradient id="gFlood" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="5%" stopColor={ALERT_TYPE_COLORS.flood} stopOpacity={0.3}/>
                      <stop offset="95%" stopColor={ALERT_TYPE_COLORS.flood} stopOpacity={0}/>
                    </linearGradient>
                    <linearGradient id="gAir" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="5%" stopColor={ALERT_TYPE_COLORS.air_quality} stopOpacity={0.3}/>
                      <stop offset="95%" stopColor={ALERT_TYPE_COLORS.air_quality} stopOpacity={0}/>
                    </linearGradient>
                    <linearGradient id="gHeat" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="5%" stopColor={ALERT_TYPE_COLORS.heat_wave} stopOpacity={0.3}/>
                      <stop offset="95%" stopColor={ALERT_TYPE_COLORS.heat_wave} stopOpacity={0}/>
                    </linearGradient>
                    <linearGradient id="gDrought" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="5%" stopColor={ALERT_TYPE_COLORS.drought} stopOpacity={0.3}/>
                      <stop offset="95%" stopColor={ALERT_TYPE_COLORS.drought} stopOpacity={0}/>
                    </linearGradient>
                  </defs>
                  <CartesianGrid strokeDasharray="3 3" stroke="var(--color-border)" />
                  <XAxis dataKey="date" tick={{ fontSize: 10 }}
                    tickFormatter={v => { const d = new Date(v); return `${d.getDate()}/${d.getMonth()+1}`; }}
                    interval={Math.floor((histStats.data.timeline?.length || 0) / 6)} />
                  <YAxis tick={{ fontSize: 10 }} allowDecimals={false} />
                  <Tooltip
                    labelFormatter={v => new Date(v).toLocaleDateString("fr-FR", { day:"numeric", month:"long" })}
                    formatter={(val: any, name: string) => [val, { flood:"Inondation", air_quality:"Qualité air", heat_wave:"Canicule", drought:"Sécheresse" }[name] || name]}
                    contentStyle={{ fontSize: 12, borderRadius: 8 }} />
                  <Legend iconType="circle" iconSize={8} wrapperStyle={{ fontSize: 11 }}
                    formatter={(v: string) => ({ flood:"Inondation", air_quality:"Qualité air", heat_wave:"Canicule", drought:"Sécheresse" }[v] || v)} />
                  <Area type="monotone" dataKey="flood"       stroke={ALERT_TYPE_COLORS.flood}       fill="url(#gFlood)"   strokeWidth={2} />
                  <Area type="monotone" dataKey="air_quality" stroke={ALERT_TYPE_COLORS.air_quality} fill="url(#gAir)"     strokeWidth={2} />
                  <Area type="monotone" dataKey="heat_wave"   stroke={ALERT_TYPE_COLORS.heat_wave}   fill="url(#gHeat)"    strokeWidth={2} />
                  <Area type="monotone" dataKey="drought"     stroke={ALERT_TYPE_COLORS.drought}     fill="url(#gDrought)" strokeWidth={2} />
                </AreaChart>
              </ResponsiveContainer>
            </div>

            {/* Right column: by type + by severity */}
            <div className="flex flex-col gap-4">
              {/* By type donut-style bars */}
              <div>
                <p className="text-xs text-text-muted mb-2">Répartition par type</p>
                <div className="space-y-2">
                  {[
                    { key: "flood",       label: "Inondation",       color: "bg-blue-500" },
                    { key: "air_quality", label: "Qualité de l'air", color: "bg-teal-500" },
                    { key: "heat_wave",   label: "Canicule",         color: "bg-red-500" },
                    { key: "drought",     label: "Sécheresse",       color: "bg-amber-500" },
                  ].map(({ key, label, color }) => {
                    const count = histStats.data.by_type[key] || 0;
                    const total = histStats.data.total || 1;
                    const pct = Math.round((count / total) * 100);
                    return (
                      <div key={key}>
                        <div className="flex justify-between text-[11px] mb-0.5">
                          <span className="text-text">{label}</span>
                          <span className="text-text-muted font-mono">{count} ({pct}%)</span>
                        </div>
                        <div className="h-2 bg-gray-100 rounded-full overflow-hidden">
                          <div className={`h-full rounded-full transition-all ${color}`} style={{ width: `${pct}%` }} />
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>

              {/* By severity */}
              <div>
                <p className="text-xs text-text-muted mb-2">Répartition par sévérité</p>
                <div className="space-y-2">
                  {[
                    { key: "warning",  label: "Avertissement", color: "bg-yellow-400" },
                    { key: "danger",   label: "Danger",        color: "bg-orange-500" },
                    { key: "critical", label: "Critique",      color: "bg-red-600" },
                  ].map(({ key, label, color }) => {
                    const count = histStats.data.by_severity[key] || 0;
                    const total = histStats.data.total || 1;
                    const pct = Math.round((count / total) * 100);
                    return (
                      <div key={key}>
                        <div className="flex justify-between text-[11px] mb-0.5">
                          <span className="text-text">{label}</span>
                          <span className="text-text-muted font-mono">{count} ({pct}%)</span>
                        </div>
                        <div className="h-2 bg-gray-100 rounded-full overflow-hidden">
                          <div className={`h-full rounded-full transition-all ${color}`} style={{ width: `${pct}%` }} />
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>
            </div>
          </div>
        ) : null}
      </div>

      {/* Filter bar */}
      <div className="bg-card border border-border rounded-xl p-4">
        <div className="flex flex-wrap items-center gap-3">
          <Filter className="w-4 h-4 text-text-muted shrink-0" />

          {/* Search */}
          <div className="relative flex-1 min-w-[180px]">
            <Search className="w-3.5 h-3.5 absolute left-2.5 top-1/2 -translate-y-1/2 text-text-muted" />
            <input
              value={search}
              onChange={e => setSearch(e.target.value)}
              placeholder="Rechercher une alerte..."
              className="w-full pl-8 pr-3 py-1.5 text-sm border border-border rounded-lg bg-background focus:outline-none focus:ring-2 focus:ring-primary"
            />
          </div>

          {/* Type */}
          <select value={filterType} onChange={e => setFilterType(e.target.value)}
            className="border border-border rounded-lg px-3 py-1.5 text-sm bg-background text-text focus:outline-none focus:ring-2 focus:ring-primary">
            {TYPES.map(t => <option key={t.value} value={t.value}>{t.label}</option>)}
          </select>

          {/* Severity */}
          <select value={filterSeverity} onChange={e => setFilterSeverity(e.target.value)}
            className="border border-border rounded-lg px-3 py-1.5 text-sm bg-background text-text focus:outline-none focus:ring-2 focus:ring-primary"
            title={SEVERITIES.find(s => s.value === filterSeverity)?.desc || ""}>
            {SEVERITIES.map(s => <option key={s.value} value={s.value} title={s.desc}>{s.label}</option>)}
          </select>

          {/* Active status */}
          <div className="flex items-center rounded-lg border border-border overflow-hidden text-sm">
            {[
              { v: "true",  l: "Non résolues", title: "Alertes encore actives" },
              { v: "",      l: "Toutes",        title: "Actives + résolues" },
              { v: "false", l: "Résolues",     title: "Alertes clôturées" },
            ].map(opt => (
              <button key={opt.v} onClick={() => setFilterActive(opt.v as any)} title={opt.title}
                className={`px-3 py-1.5 transition ${filterActive === opt.v ? "bg-primary text-white" : "bg-background text-text hover:bg-border/50"}`}>
                {opt.l}
              </button>
            ))}
          </div>

          {/* Reset */}
          {hasFilters && (
            <button onClick={resetFilters} className="flex items-center gap-1 text-xs text-text-muted hover:text-danger transition">
              <X className="w-3.5 h-3.5" /> Réinitialiser
            </button>
          )}
        </div>
      </div>

      {/* Alert list */}
      {alerts.loading ? <LoadingSpinner /> : (
        <Card
          title="Liste des alertes"
          subtitle={`${filtered.length} résultat${filtered.length !== 1 ? "s" : ""}`}
          icon={<Bell className="w-5 h-5" />}
          headerAction={
            filterActive === "true" && filtered.length > 0 ? (
              <button onClick={handleResolveAll} disabled={resolvingAll}
                className="flex items-center gap-1.5 text-xs px-3 py-1.5 rounded-lg border border-orange-200 bg-orange-50 text-orange-700 hover:bg-orange-100 transition disabled:opacity-50">
                {resolvingAll
                  ? <span className="w-3 h-3 border-2 border-orange-300 border-t-orange-600 rounded-full animate-spin" />
                  : <ShieldOff className="w-3.5 h-3.5" />}
                Tout résoudre
              </button>
            ) : undefined
          }
        >
          {filtered.length === 0 ? (
            <div className="text-center py-12 text-text-muted">
              <Bell className="w-12 h-12 mx-auto mb-3 opacity-20" />
              <p>Aucune alerte{hasFilters ? " pour ces filtres" : " active"}</p>
              {hasFilters && (
                <button onClick={resetFilters} className="text-xs mt-2 text-primary hover:underline">
                  Réinitialiser les filtres
                </button>
              )}
            </div>
          ) : (
            <div className="divide-y divide-border">
              {filtered.map((alert: any) => (
                <div key={alert.id}
                  className={`flex items-stretch gap-0 transition-colors hover:bg-bg/60 ${!alert.is_active ? "opacity-70" : ""}`}>
                  {/* Severity accent bar */}
                  <div className={`w-1 shrink-0 rounded-l-sm ${
                    !alert.is_active ? "bg-gray-300"
                    : alert.severity === "critical" ? "bg-red-500"
                    : alert.severity === "danger"   ? "bg-orange-500"
                    : alert.severity === "warning"  ? "bg-yellow-400"
                    : "bg-blue-400"
                  }`} />

                  <div className="flex-1 flex items-start gap-3 px-4 py-4 min-w-0">
                    {/* Severity icon */}
                    <div className={`shrink-0 mt-0.5 w-8 h-8 rounded-lg flex items-center justify-center ${
                      !alert.is_active ? "bg-gray-100"
                      : alert.severity === "critical" ? "bg-red-50"
                      : alert.severity === "danger"   ? "bg-orange-50"
                      : alert.severity === "warning"  ? "bg-yellow-50"
                      : "bg-blue-50"
                    }`}>
                      {alert.is_active
                        ? (severityIcon[alert.severity] || <Bell className="w-4 h-4 text-blue-400" />)
                        : <CheckCircle className="w-4 h-4 text-gray-400" />}
                    </div>

                    {/* Main content */}
                    <div className="flex-1 min-w-0">
                      <div className="flex items-start justify-between gap-3 flex-wrap">
                        {/* Left: title + location + description */}
                        <div className="min-w-0">
                          <h4 className="font-semibold text-sm text-text leading-tight">{alert.title}</h4>
                          {alert.locations?.name && (
                            <p className="text-xs text-text-muted mt-0.5 flex items-center gap-1">
                              <span className="text-[10px]">📍</span> {alert.locations.name}
                            </p>
                          )}
                          {alert.description && (
                            <p className="text-xs text-text-secondary mt-1 leading-snug">{alert.description}</p>
                          )}
                          {/* Badges */}
                          <div className="flex flex-wrap gap-1.5 mt-2">
                            <span className={`text-[10px] px-2 py-0.5 rounded-full font-medium border ${typeBadge[alert.alert_type] || "bg-gray-100 text-gray-700 border-gray-200"}`}>
                              {TYPE_LABELS[alert.alert_type] || alert.alert_type}
                            </span>
                            <span
                              className={`text-[10px] px-2 py-0.5 rounded-full font-medium border ${severityBadge[alert.severity] || "bg-gray-100 text-gray-700 border-gray-200"}`}
                              title={SEVERITIES.find(s => s.value === alert.severity)?.desc || ""}>
                              {SEVERITY_FR[alert.severity] || alert.severity}
                            </span>
                            {!alert.is_active && (
                              <span className="text-[10px] px-2 py-0.5 rounded-full font-medium bg-gray-100 text-gray-500 border border-gray-200 flex items-center gap-1">
                                <CheckCircle className="w-2.5 h-2.5" /> Résolue
                              </span>
                            )}
                          </div>
                        </div>

                        {/* Right: timestamps + action */}
                        <div className="shrink-0 flex flex-col items-end gap-2">
                          <div className="text-right space-y-0.5">
                            <p className="text-[10px] text-text-muted flex items-center gap-1 justify-end">
                              <Clock className="w-2.5 h-2.5" />
                              Début : <strong className="text-text font-medium">{formatDateTime(alert.start_date || alert.created_at)}</strong>
                            </p>
                            {alert.is_active ? (
                              <p className="text-[10px] text-text-muted">
                                Durée : <strong className="text-primary font-semibold">{formatDuration(alert.start_date || alert.created_at)}</strong>
                              </p>
                            ) : (
                              <p className="text-[10px] text-text-muted">
                                Durée : <span className="font-medium">{formatDuration(alert.start_date || alert.created_at, alert.end_date)}</span>
                              </p>
                            )}
                          </div>
                          {alert.is_active ? (
                            <button
                              onClick={() => handleResolve(alert.id)}
                              disabled={resolving === alert.id}
                              title="Marquer comme résolue"
                              className="flex items-center gap-1.5 text-xs px-3 py-1.5 rounded-lg border border-green-200 bg-green-50 text-green-700 hover:bg-green-100 font-medium transition disabled:opacity-50">
                              {resolving === alert.id
                                ? <span className="w-3 h-3 border-2 border-green-300 border-t-green-600 rounded-full animate-spin" />
                                : <CheckCircle className="w-3.5 h-3.5" />}
                              Résoudre
                            </button>
                          ) : (
                            <button
                              onClick={() => handleDelete(alert.id)}
                              disabled={deleting === alert.id}
                              title="Supprimer définitivement"
                              className="flex items-center gap-1.5 text-xs px-3 py-1.5 rounded-lg border border-red-200 bg-red-50 text-red-600 hover:bg-red-100 font-medium transition disabled:opacity-50">
                              {deleting === alert.id
                                ? <span className="w-3 h-3 border-2 border-red-300 border-t-red-600 rounded-full animate-spin" />
                                : <Trash2 className="w-3.5 h-3.5" />}
                              Supprimer
                            </button>
                          )}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </Card>
      )}
    </div>
  );
}
